// ================================================================================================
//  WaveChart - M13: THE CASCADE SEA'S LOCAL PLANES, GENERATED BY THE LATTICE.
//
//  Everything else in the water is read at a PLACE: the bed, the tide, the sea-state scale, the
//  swell shadow, the solved field. The FFT cascades cannot be -- they are periodic patches OF A
//  PLANE (756 / 186 / 47 m, sampled frac(xz / L)), and a sphere has no chart that is both global
//  and isometric (Gauss's theorema egregium: curvature is an invariant of isometries). So the sea
//  needs local planes, and the only question is where they come from.
//
//  THEY COME FROM THE LATTICE, not from a declaration. Each cell of the cube quadtree at a chart
//  level carries the tangent frame at its centre -- east, up, north, the rotor a place is carried
//  into by the sandwich -- and an offset hashed from its own address. A place's cascade coordinate
//  in that cell is its projection onto that frame, plus the offset. Nothing is anchored at the
//  Merrimack, at a boat, or at a camera: two hulls a metre apart read the same sea wherever they
//  are, which is what a physics twin and a second player both need.
//
//  CELLS MEET IN A BAND, AND THE REALIZATIONS BLEND THERE. A hard switch would be a seam; a plain
//  lerp would halve the variance in the middle of the band (two independent draws averaged). The
//  operator that does not is the variance-preserving one:
//
//      S = sum_i w_i S_i / sqrt(sum_i w_i^2)
//
//  which for Gaussian content -- an FFT sea is a sum of many random-phase modes, so it is
//  Gaussian to the eye and to the statistics -- keeps each point's distribution exactly and the
//  spectrum wherever the weights vary slowly against the waves (Heitz & Neyret, "High-Performance
//  By-Example Noise using a Histogram-Preserving Blending Operator", HPG 2018). The weights are a
//  partition of unity over the cell and its neighbours, so they sum to 1 and the law is continuous
//  everywhere, including across a cube-face edge (a neighbour is CANONICALIZED by re-addressing a
//  direction inside it, so both sides of an edge name the same chart).
//
//  ONLY THE LINEAR CHANNELS BLEND. The displacement, its slopes and the Jacobian's components are
//  linear in the realization and blend with these weights; every nonlinear quantity -- the
//  Jacobian's determinant, the foam triggers, the Newton step that inverts the Gerstner map -- is
//  formed AFTER the blend, from the blended channels. The fold's sigma^2 is a statistic of the
//  spectrum and no blend touches it.
//
//  WHAT THIS COSTS, AND ITS ONE KNOWN LIMIT. At the default level the cells are 190-400 km, so
//  almost every place reads ONE chart (the tangent projection's wavelength error there is at most
//  (d/R)^2/2 = 0.05 %, and the spectrum's heading drifts by d tan(lat)/R -- 1.7 degrees at 43 N).
//  In a band two charts are read, at a corner four. Narrowband content -- the swell cascade -- is
//  coherent, so where two charts meet out of phase the blend beats: the swell's amplitude swings
//  over kilometres along the band's centre. It is measured, not hidden (the probe's band pose),
//  and the cure is to stop drawing swell from a periodic patch at all (planetary components on
//  great circles, M13's follow-on F).
// ================================================================================================
#pragma once

#include "core/Lattice.h"

#include <cmath>
#include <cstdint>

namespace ga {

bool RunWaveChartSelfTest();   // sim/WaveChartTest.cpp

struct WaveChart {
    // Scene properties (water.waveChart), not constants: the level the planes are cut at and the
    // width of the band they blend across.
    int level = 5;             // cube-quadtree level: cells 190-400 km
    double bandM = 5000.0;     // the blend band, metres of ground
    double planetR = 6371000.0;

    static constexpr int kMax = 4;   // a cell, two edge neighbours, one diagonal

    // ONE CHART'S PLANE, as the lattice makes it: a cell's origin on the sphere, its axes, and
    // its hashed offset. It is a function of the cell's ADDRESS alone, so it can be found once
    // for a neighbourhood -- a hull's stations, a bank tile's texels -- and the per-point work is
    // then two dot products.
    struct Frame {
        double org[3] = {0.0, 0.0, 0.0};   // the cell's centre on the sphere (metres)
        double e[3] = {1.0, 0.0, 0.0};     // east at that centre
        double n[3] = {0.0, 0.0, 1.0};     // north there
        double off[2] = {0.0, 0.0};        // the cell's own offset in its plane
        uint64_t key = 0;
    };

    // THE NEIGHBOURHOOD of a place: its own cell, the metric that carries the band's metres into
    // the cell's uv, and the four planes that can touch it (its own, the neighbour across the
    // nearer x edge, across the nearer y edge, and the diagonal -- in that order, always).
    struct Cell {
        uint32_t face = 0;
        int ix = 0, iy = 0, dx = 0, dy = 0;
        double mPerU = 0.0, mPerV = 0.0;
        Frame f[4];
    };

    struct Chart {
        double u[2] = {0.0, 0.0};   // the place in this chart's plane (metres), offset included
        double w = 0.0;             // its share of the blend; the shares sum to 1
        // This chart's (east, north) said in the PLACE's own (east, north): a 2x2 rotation, so a
        // vector the cascades answer in chart axes (the Gerstner lateral term, the slopes) can be
        // added to the others. The charts differ by the meridian convergence between their
        // centres -- under two degrees at this level -- so this is a small rotation, never a
        // reflection.
        double rot[4] = {1.0, 0.0, 0.0, 1.0};   // (e.e, n.e, e.n, n.n)
        uint64_t cell = 0;                       // the address, for the hash and for instruments
    };

    // THE HASH: a cell's own offset, so two charts that meet are decorrelated draws of the one
    // spectrum rather than the same crests at an arbitrary lag. Deterministic in the address
    // alone -- no clock, no camera, no order of evaluation -- which is what makes two processors
    // and two machines agree. (splitmix64's mixer.)
    static uint64_t Mix(uint64_t x) {
        x += 0x9E3779B97F4A7C15ull;
        x = (x ^ (x >> 30)) * 0xBF58476D1CE4E5B9ull;
        x = (x ^ (x >> 27)) * 0x94D049BB133111EBull;
        return x ^ (x >> 31);
    }
    static uint64_t Key(uint32_t face, int lvl, int ix, int iy) {
        return (uint64_t(face) << 58) | (uint64_t(lvl & 63) << 52) |
               (uint64_t(uint32_t(ix)) << 26) | uint64_t(uint32_t(iy));
    }
    static void OffsetOf(uint64_t key, double out[2]) {
        const uint64_t h = Mix(key);
        // 100 km of offset: past every cascade's period (756 m), so each wraps it differently.
        out[0] = double(h & 0xFFFFFFFFu) / 4294967296.0 * 1.0e5;
        out[1] = double(h >> 32) / 4294967296.0 * 1.0e5;
    }

    // The local frame at a unit direction, in the planet frame: up = the direction, east =
    // d(dir)/dlon normalized, north = east x up -- THE ENGINE'S OWN ORDER (this planet frame is an
    // odd permutation of ECEF, so up x east would answer south: FrameLoop's det check exists for
    // that slip). At a pole east degenerates and the face's own axis stands in.
    static void FrameAt(const double d[3], double east[3], double north[3]) {
        const double yl = std::sqrt(d[0] * d[0] + d[2] * d[2]);
        if (yl > 1e-12) {
            east[0] = -d[2] / yl;
            east[1] = 0.0;
            east[2] = d[0] / yl;
        } else {
            east[0] = 1.0;
            east[1] = 0.0;
            east[2] = 0.0;
        }
        north[0] = east[1] * d[2] - east[2] * d[1];
        north[1] = east[2] * d[0] - east[0] * d[2];
        north[2] = east[0] * d[1] - east[1] * d[0];
    }

    // THE CHARTS THAT TOUCH A PLACE (a unit direction in the planet frame). ALWAYS four, in one
    // order -- the cell, its neighbour across the nearer x edge, across the nearer y edge, and
    // the diagonal -- with shares that sum to 1 exactly. A share is usually 0 (a place in a
    // cell's plateau reads one chart and three zeros).
    //
    // THE SKIP IS PART OF THE LAW, so that both processors run one expression: a reader may skip
    // SAMPLING a chart whose share is below kSkip, and every share still counts in the norm. The
    // hull's twin skips to stay cheap; the kernel skips to stay cheap; the result is the same
    // number to a part in 10^4 of a millimetre, rather than two laws that nearly agree.
    static constexpr double kSkip = 1.0e-4;

    // THE NEIGHBOURHOOD of a place: the cells, their planes and the metric. Everything in here is
    // a function of the ADDRESS, so it is found once for a hull's stations or a tile's texels.
    Cell CellAt(const double dir[3]) const {
        Cell cell;
        const int n = 1 << level;
        double uv[2];
        cell.face = CubeFaceOfDir(dir, uv);
        cell.ix = Clampi(int(std::floor(uv[0] * double(n))), 0, n - 1);
        cell.iy = Clampi(int(std::floor(uv[1] * double(n))), 0, n - 1);
        cell.dx = (uv[0] * double(n) - double(cell.ix) < 0.5) ? -1 : 1;
        cell.dy = (uv[1] * double(n) - double(cell.iy) < 0.5) ? -1 : 1;
        // The cell's metric: metres of ground per uv unit at its centre. The band is stated in
        // metres of ground, so it is carried into uv through this.
        const double cu = (double(cell.ix) + 0.5) / double(n);
        const double cv = (double(cell.iy) + 0.5) / double(n);
        const double h = 0.25 / double(n);
        double a[3], b[3];
        ComposeCubeDir(cell.face, cu + h, cv, a);
        ComposeCubeDir(cell.face, cu - h, cv, b);
        cell.mPerU = planetR * Dist(a, b) / (2.0 * h);
        ComposeCubeDir(cell.face, cu, cv + h, a);
        ComposeCubeDir(cell.face, cu, cv - h, b);
        cell.mPerV = planetR * Dist(a, b) / (2.0 * h);
        const int nx[4] = {0, cell.dx, 0, cell.dx};
        const int ny[4] = {0, 0, cell.dy, cell.dy};
        for (int k = 0; k < kMax; ++k) {
            Build(cell.face, cell.ix + nx[k], cell.iy + ny[k], n, cell.f[k]);
        }
        return cell;
    }

    // Does a neighbourhood still describe this place? (Its own cell and its choice of neighbours
    // are what a memo may not outlive; both change hundreds of kilometres apart.)
    bool Holds(const Cell& cell, const double dir[3]) const {
        const int n = 1 << level;
        double uv[2];
        const uint32_t face = CubeFaceOfDir(dir, uv);
        const int ix = Clampi(int(std::floor(uv[0] * double(n))), 0, n - 1);
        const int iy = Clampi(int(std::floor(uv[1] * double(n))), 0, n - 1);
        if (face != cell.face || ix != cell.ix || iy != cell.iy) return false;
        const int dx = (uv[0] * double(n) - double(ix) < 0.5) ? -1 : 1;
        const int dy = (uv[1] * double(n) - double(iy) < 0.5) ? -1 : 1;
        return dx == cell.dx && dy == cell.dy;
    }

    // THE CHARTS AT A PLACE inside that neighbourhood: each plane's coordinate for this point,
    // its share, and its axes said in the place's own east/north. Always four, shares summing to
    // 1 exactly; a reader may skip SAMPLING one below kSkip and the norm still counts it.
    // The distance, in metres of ground, from a place to the cell edge its chosen neighbour lies
    // across -- one per axis. The blend's only input, so it is written once here and read by the
    // hull's twin, by the kernel's per-tile rows, and by the gate.
    void EdgeM(const Cell& cell, const double dir[3], double& ex, double& ey) const {
        const int n = 1 << level;
        double uv[2];
        CubeFaceOfDir(dir, uv);
        const double fx = uv[0] * double(n), fy = uv[1] * double(n);
        const double sx = fx - std::floor(fx), sy = fy - std::floor(fy);
        ex = ((cell.dx < 0) ? sx : 1.0 - sx) * cell.mPerU / double(n);
        ey = ((cell.dy < 0) ? sy : 1.0 - sy) * cell.mPerV / double(n);
    }
    // The shares from those two distances: 1/2 exactly on an edge, 1 a half-band inside it, the
    // neighbour taking the rest -- smoothstep, so the law is C1 where charts change hands.
    void Shares(double edgeX, double edgeY, double w[kMax]) const {
        const double band = (bandM > 1.0) ? bandM : 1.0;
        const double wx = Smooth(0.5 + edgeX / band), wy = Smooth(0.5 + edgeY / band);
        w[0] = wx * wy;
        w[1] = (1.0 - wx) * wy;
        w[2] = wx * (1.0 - wy);
        w[3] = (1.0 - wx) * (1.0 - wy);
    }

    int At(const Cell& cell, const double dir[3], Chart out[kMax]) const {
        double edgeX = 0.0, edgeY = 0.0;
        EdgeM(cell, dir, edgeX, edgeY);
        double ws[kMax];
        Shares(edgeX, edgeY, ws);
        double pe[3], pn[3], p[3];
        FrameAt(dir, pe, pn);
        for (int i = 0; i < 3; ++i) p[i] = dir[i] * planetR;
        for (int k = 0; k < kMax; ++k) {
            const Frame& f = cell.f[k];
            Chart& c = out[k];
            c.w = ws[k];
            c.cell = f.key;
            const double r[3] = {p[0] - f.org[0], p[1] - f.org[1], p[2] - f.org[2]};
            c.u[0] = r[0] * f.e[0] + r[1] * f.e[1] + r[2] * f.e[2] + f.off[0];
            c.u[1] = r[0] * f.n[0] + r[1] * f.n[1] + r[2] * f.n[2] + f.off[1];
            c.rot[0] = f.e[0] * pe[0] + f.e[1] * pe[1] + f.e[2] * pe[2];
            c.rot[1] = f.n[0] * pe[0] + f.n[1] * pe[1] + f.n[2] * pe[2];
            c.rot[2] = f.e[0] * pn[0] + f.e[1] * pn[1] + f.e[2] * pn[2];
            c.rot[3] = f.n[0] * pn[0] + f.n[1] * pn[1] + f.n[2] * pn[2];
        }
        return kMax;
    }

    // The one-shot, for a caller with a single place to ask about.
    int At(const double dir[3], Chart out[kMax]) const { return At(CellAt(dir), dir, out); }

    // A point of the sphere (planet frame, metres) in one chart's plane: the tangent projection
    // about the cell's own origin -- the sandwich's tangent part -- plus the cell's offset. The
    // kernel's per-tile rows are this function sampled at a tile's corner and differenced across
    // it, so there is one expression for "where is this in that plane".
    static void UOf(const Frame& f, const double p[3], double u[2]) {
        const double r[3] = {p[0] - f.org[0], p[1] - f.org[1], p[2] - f.org[2]};
        u[0] = r[0] * f.e[0] + r[1] * f.e[1] + r[2] * f.e[2] + f.off[0];
        u[1] = r[0] * f.n[0] + r[1] * f.n[1] + r[2] * f.n[2] + f.off[1];
    }

    // How many charts actually carry this place -- 1 in a plateau, 2 in a band, 4 at a corner.
    // An instrument and a loop bound, never a change of the law.
    static int Significant(const Chart c[kMax]) {
        int n = 0;
        for (int i = 0; i < kMax; ++i) {
            if (c[i].w >= kSkip) ++n;
        }
        return n;
    }

    // The blend's norm, said once so both processors read the same expression.
    static double Norm(const Chart* c, int n) {
        double s2 = 0.0;
        for (int i = 0; i < n; ++i) s2 += c[i].w * c[i].w;
        return (s2 > 1e-12) ? std::sqrt(s2) : 1.0;
    }

private:
    static int Clampi(int v, int lo, int hi) { return (v < lo) ? lo : (v > hi ? hi : v); }
    static double Dist(const double a[3], const double b[3]) {
        const double dx = a[0] - b[0], dy = a[1] - b[1], dz = a[2] - b[2];
        return std::sqrt(dx * dx + dy * dy + dz * dz);
    }
    static double Smooth(double t) {
        const double x = (t < 0.0) ? 0.0 : (t > 1.0 ? 1.0 : t);
        return x * x * (3.0 - 2.0 * x);
    }

    // One cell's plane, CANONICALLY. A neighbour index may run off its face; stepping the uv past
    // the edge still names a direction (the face's plane extends), so that direction is
    // re-addressed to find whose cell it really is. Both sides of a face edge then build the same
    // plane from the same address, which is what keeps the blend continuous there.
    void Build(uint32_t face, int ix, int iy, int n, Frame& f) const {
        double dc[3];
        ComposeCubeDir(face, (double(ix) + 0.5) / double(n), (double(iy) + 0.5) / double(n), dc);
        if (ix < 0 || iy < 0 || ix >= n || iy >= n) {
            double uv2[2];
            const uint32_t f2 = CubeFaceOfDir(dc, uv2);
            const int jx = Clampi(int(std::floor(uv2[0] * double(n))), 0, n - 1);
            const int jy = Clampi(int(std::floor(uv2[1] * double(n))), 0, n - 1);
            face = f2;
            ix = jx;
            iy = jy;
            ComposeCubeDir(face, (double(ix) + 0.5) / double(n), (double(iy) + 0.5) / double(n),
                           dc);
        }
        FrameAt(dc, f.e, f.n);
        for (int i = 0; i < 3; ++i) f.org[i] = dc[i] * planetR;
        f.key = Key(face, level, ix, iy);
        OffsetOf(f.key, f.off);
    }
};

}  // namespace ga
