// ================================================================================================
//  WaveChart - M13: THE CASCADE SEA'S LOCAL PLANES, GENERATED BY THE LATTICE.
//
//  Everything else in the water is read at a PLACE: the bed, the tide, the sea-state scale, the
//  swell shadow, the solved field. The FFT cascades cannot be -- they are periodic patches OF A
//  PLANE (756 / 186 / 47 m, sampled frac(xz / L)), and a sphere has no chart that is both global
//  and isometric (Gauss's theorema egregium: curvature is an invariant of isometries). So the sea
//  needs local planes, and the only question is where they come from.
//
//  THEY COME FROM THE LATTICE, not from a declaration. Each cell of the cube quadtree at a chart
//  level carries the tangent frame at its centre -- east, up, north, the rotor a place is carried
//  into by the sandwich -- and an offset hashed from its own address. A place's cascade coordinate
//  in that cell is its projection onto that frame, plus the offset. Nothing is anchored at the
//  Merrimack, at a boat, or at a camera: two hulls a metre apart read the same sea wherever they
//  are, which is what a physics twin and a second player both need.
//
//  CELLS MEET IN A BAND, AND THE REALIZATIONS BLEND THERE. A hard switch would be a seam; a plain
//  lerp would halve the variance in the middle of the band (two independent draws averaged). The
//  operator that does not is the variance-preserving one:
//
//      S = sum_i w_i S_i / sqrt(sum_i w_i^2)
//
//  which for Gaussian content -- an FFT sea is a sum of many random-phase modes, so it is
//  Gaussian to the eye and to the statistics -- keeps each point's distribution exactly and the
//  spectrum wherever the weights vary slowly against the waves (Heitz & Neyret, "High-Performance
//  By-Example Noise using a Histogram-Preserving Blending Operator", HPG 2018). The weights are a
//  partition of unity over the cell and its neighbours, so they sum to 1 and the law is continuous
//  everywhere, including across a cube-face edge (a neighbour is CANONICALIZED by re-addressing a
//  direction inside it, so both sides of an edge name the same chart).
//
//  ONLY THE LINEAR CHANNELS BLEND. The displacement, its slopes and the Jacobian's components are
//  linear in the realization and blend with these weights; every nonlinear quantity -- the
//  Jacobian's determinant, the foam triggers, the Newton step that inverts the Gerstner map -- is
//  formed AFTER the blend, from the blended channels. The fold's sigma^2 is a statistic of the
//  spectrum and no blend touches it.
//
//  WHAT THIS COSTS, AND ITS ONE KNOWN LIMIT. At the default level the cells are 190-400 km, so
//  almost every place reads ONE chart (the tangent projection's wavelength error there is at most
//  (d/R)^2/2 = 0.05 %, and the spectrum's heading drifts by d tan(lat)/R -- 1.7 degrees at 43 N).
//  In a band two charts are read, at a corner four. Narrowband content -- the swell cascade -- is
//  coherent, so where two charts meet out of phase the blend beats: the swell's amplitude swings
//  over kilometres along the band's centre. It is measured, not hidden (the probe's band pose),
//  and the cure is to stop drawing swell from a periodic patch at all (planetary components on
//  great circles, M13's follow-on F).
// ================================================================================================
#pragma once

#include "core/Lattice.h"

#include <cmath>
#include <cstdint>

namespace ga {

bool RunWaveChartSelfTest();   // sim/WaveChartTest.cpp

struct WaveChart {
    // Scene properties (water.waveChart), not constants: the level the planes are cut at and the
    // width of the band they blend across.
    int level = 5;             // cube-quadtree level: cells 190-400 km
    double bandM = 5000.0;     // the blend band, metres of ground
    double planetR = 6371000.0;

    static constexpr int kMax = 4;   // a cell, two edge neighbours, one diagonal

    struct Chart {
        double u[2] = {0.0, 0.0};   // the place in this chart's plane (metres), offset included
        double w = 0.0;             // its share of the blend; the shares sum to 1
        // This chart's (east, north) said in the PLACE's own (east, north): a 2x2 rotation, so a
        // vector the cascades answer in chart axes (the Gerstner lateral term, the slopes) can be
        // added to the others. The charts differ by the meridian convergence between their
        // centres -- under two degrees at this level -- so this is a small rotation, never a
        // reflection.
        double rot[4] = {1.0, 0.0, 0.0, 1.0};   // (e.e, n.e, e.n, n.n)
        uint64_t cell = 0;                       // the address, for the hash and for instruments
    };

    // THE HASH: a cell's own offset, so two charts that meet are decorrelated draws of the one
    // spectrum rather than the same crests at an arbitrary lag. Deterministic in the address
    // alone -- no clock, no camera, no order of evaluation -- which is what makes two processors
    // and two machines agree. (splitmix64's mixer.)
    static uint64_t Mix(uint64_t x) {
        x += 0x9E3779B97F4A7C15ull;
        x = (x ^ (x >> 30)) * 0xBF58476D1CE4E5B9ull;
        x = (x ^ (x >> 27)) * 0x94D049BB133111EBull;
        return x ^ (x >> 31);
    }
    static uint64_t Key(uint32_t face, int lvl, int ix, int iy) {
        return (uint64_t(face) << 58) | (uint64_t(lvl & 63) << 52) |
               (uint64_t(uint32_t(ix)) << 26) | uint64_t(uint32_t(iy));
    }
    static void OffsetOf(uint64_t key, double out[2]) {
        const uint64_t h = Mix(key);
        // 100 km of offset: past every cascade's period (756 m), so each wraps it differently.
        out[0] = double(h & 0xFFFFFFFFu) / 4294967296.0 * 1.0e5;
        out[1] = double(h >> 32) / 4294967296.0 * 1.0e5;
    }

    // The local frame at a unit direction, in the planet frame: up = the direction, east =
    // d(dir)/dlon normalized, north = east x up -- THE ENGINE'S OWN ORDER (this planet frame is an
    // odd permutation of ECEF, so up x east would answer south: FrameLoop's det check exists for
    // that slip). At a pole east degenerates and the face's own axis stands in.
    static void FrameAt(const double d[3], double east[3], double north[3]) {
        const double yl = std::sqrt(d[0] * d[0] + d[2] * d[2]);
        if (yl > 1e-12) {
            east[0] = -d[2] / yl;
            east[1] = 0.0;
            east[2] = d[0] / yl;
        } else {
            east[0] = 1.0;
            east[1] = 0.0;
            east[2] = 0.0;
        }
        north[0] = east[1] * d[2] - east[2] * d[1];
        north[1] = east[2] * d[0] - east[0] * d[2];
        north[2] = east[0] * d[1] - east[1] * d[0];
    }

    // THE CHARTS THAT TOUCH A PLACE (a unit direction in the planet frame). Returns how many
    // (1 in a cell's plateau, 2 in a band, 4 at a corner); the shares sum to 1.
    int At(const double dir[3], Chart out[kMax]) const {
        const int n = 1 << level;
        double uv[2];
        const uint32_t face = CubeFaceOfDir(dir, uv);
        const double fx = uv[0] * double(n), fy = uv[1] * double(n);
        int ix = int(std::floor(fx)), iy = int(std::floor(fy));
        if (ix < 0) ix = 0;
        if (iy < 0) iy = 0;
        if (ix > n - 1) ix = n - 1;
        if (iy > n - 1) iy = n - 1;
        // The place's own frame and its point on the sphere.
        double pe[3], pn[3], p[3];
        FrameAt(dir, pe, pn);
        for (int i = 0; i < 3; ++i) p[i] = dir[i] * planetR;

        // The cell's metric: metres of ground per uv unit at its centre, along each axis. The
        // band is stated in metres, so it has to be carried into uv through this.
        const double cu = (double(ix) + 0.5) / double(n), cv = (double(iy) + 0.5) / double(n);
        const double h = 0.25 / double(n);
        double a[3], b[3];
        ComposeCubeDir(face, cu + h, cv, a);
        ComposeCubeDir(face, cu - h, cv, b);
        const double mPerU = planetR * Dist(a, b) / (2.0 * h);
        ComposeCubeDir(face, cu, cv + h, a);
        ComposeCubeDir(face, cu, cv - h, b);
        const double mPerV = planetR * Dist(a, b) / (2.0 * h);

        // The share along each axis: 1/2 exactly on the edge, 1 a half-band inside it, and the
        // neighbour takes the rest. smoothstep, so the law is C1 where the charts change hands.
        const double sx = fx - double(ix), sy = fy - double(iy);
        const int dx = (sx < 0.5) ? -1 : 1, dy = (sy < 0.5) ? -1 : 1;
        const double edgeX = ((sx < 0.5) ? sx : 1.0 - sx) * mPerU / double(n);
        const double edgeY = ((sy < 0.5) ? sy : 1.0 - sy) * mPerV / double(n);
        const double wx = Smooth(0.5 + edgeX / (bandM > 1.0 ? bandM : 1.0));
        const double wy = Smooth(0.5 + edgeY / (bandM > 1.0 ? bandM : 1.0));

        const int nx[4] = {0, dx, 0, dx};
        const int ny[4] = {0, 0, dy, dy};
        const double ws[4] = {wx * wy, (1.0 - wx) * wy, wx * (1.0 - wy), (1.0 - wx) * (1.0 - wy)};
        int count = 0;
        for (int k = 0; k < 4; ++k) {
            if (ws[k] < 1.0e-4) continue;
            Chart& c = out[count];
            c.w = ws[k];
            Build(face, ix + nx[k], iy + ny[k], n, p, pe, pn, c);
            ++count;
        }
        // A share dropped below the floor is given back to the largest, so the shares still sum
        // to 1 exactly and the norm below is the one both processors compute.
        double sum = 0.0;
        int big = 0;
        for (int k = 0; k < count; ++k) {
            sum += out[k].w;
            if (out[k].w > out[big].w) big = k;
        }
        if (count > 0) out[big].w += 1.0 - sum;
        return count;
    }

    // The blend's norm, said once so both processors read the same expression.
    static double Norm(const Chart* c, int n) {
        double s2 = 0.0;
        for (int i = 0; i < n; ++i) s2 += c[i].w * c[i].w;
        return (s2 > 1e-12) ? std::sqrt(s2) : 1.0;
    }

private:
    static double Dist(const double a[3], const double b[3]) {
        const double dx = a[0] - b[0], dy = a[1] - b[1], dz = a[2] - b[2];
        return std::sqrt(dx * dx + dy * dy + dz * dz);
    }
    static double Smooth(double t) {
        const double x = (t < 0.0) ? 0.0 : (t > 1.0 ? 1.0 : t);
        return x * x * (3.0 - 2.0 * x);
    }

    // One chart, CANONICALLY. A neighbour index may run off its face; stepping the uv past the
    // edge still names a direction (the face's plane extends), so that direction is re-addressed
    // to find whose cell it really is. Both sides of a face edge then build the same chart from
    // the same address, which is what keeps the blend continuous there.
    void Build(uint32_t face, int ix, int iy, int n, const double p[3], const double pe[3],
               const double pn[3], Chart& c) const {
        double dc[3];
        ComposeCubeDir(face, (double(ix) + 0.5) / double(n), (double(iy) + 0.5) / double(n), dc);
        if (ix < 0 || iy < 0 || ix >= n || iy >= n) {
            double uv2[2];
            const uint32_t f2 = CubeFaceOfDir(dc, uv2);
            int jx = int(std::floor(uv2[0] * double(n))), jy = int(std::floor(uv2[1] * double(n)));
            if (jx < 0) jx = 0;
            if (jy < 0) jy = 0;
            if (jx > n - 1) jx = n - 1;
            if (jy > n - 1) jy = n - 1;
            face = f2;
            ix = jx;
            iy = jy;
            ComposeCubeDir(face, (double(ix) + 0.5) / double(n), (double(iy) + 0.5) / double(n),
                           dc);
        }
        double ce[3], cn[3];
        FrameAt(dc, ce, cn);
        c.cell = Key(face, level, ix, iy);
        double off[2];
        OffsetOf(c.cell, off);
        // The place in this chart's plane: the tangent projection of the point about the cell's
        // own origin (its centre on the sphere), which is the sandwich's tangent part.
        const double r[3] = {p[0] - dc[0] * planetR, p[1] - dc[1] * planetR, p[2] - dc[2] * planetR};
        c.u[0] = r[0] * ce[0] + r[1] * ce[1] + r[2] * ce[2] + off[0];
        c.u[1] = r[0] * cn[0] + r[1] * cn[1] + r[2] * cn[2] + off[1];
        // This chart's axes said in the place's own, for the vector channels.
        c.rot[0] = ce[0] * pe[0] + ce[1] * pe[1] + ce[2] * pe[2];
        c.rot[1] = cn[0] * pe[0] + cn[1] * pe[1] + cn[2] * pe[2];
        c.rot[2] = ce[0] * pn[0] + ce[1] * pn[1] + ce[2] * pn[2];
        c.rot[3] = cn[0] * pn[0] + cn[1] * pn[1] + cn[2] * pn[2];
    }
};

}  // namespace ga
