// ================================================================================================
//  WaveChartTest - the gate for the cascade sea's local planes (sim/WaveChart.h).
//
//  What has to be true of a chart family generated by the lattice, stated as checks rather than
//  as claims in a commit message:
//
//   1. PARTITION. The shares sum to 1 at every place, never more than four charts answer, and
//      each chart's identity is a canonical cell address -- including across a cube-face edge,
//      where both sides must name the SAME pair of charts or the sea changes at the seam.
//   2. CONTINUITY. Walking a line across a cell edge, a synthetic realization read through the
//      blend moves smoothly: the largest step between samples 1 m apart stays at the scale the
//      field itself moves, not at the scale of the two charts' difference (which is what a hard
//      switch would show).
//   3. VARIANCE. The whole reason for sum(w S)/sqrt(sum w^2) rather than a lerp: a Gaussian field
//      blended across the band keeps its variance. Measured on a synthetic Gaussian (a hundred
//      random-phase modes) against the same field read from one chart.
//   4. THE METRIC. A chart is a tangent projection, so distances in it are short by (d/R)^2/2 at
//      the cell's edge; at the shipped level that must stay under a tenth of a percent, which is
//      what makes one plane honest over a cell 400 km across.
//   5. DETERMINISM. The same place answers the same charts, offsets included, on repeated calls:
//      a hull's physics may not depend on anything but the scene and the clock.
// ================================================================================================
#include "sim/WaveChart.h"

#include "core/Common.h"

#include <cmath>
#include <cstdio>
#include <vector>

namespace ga {

namespace {

// A synthetic GAUSSIAN realization of a broadband sea, in one chart's plane: a hundred modes with
// fixed pseudo-random phases and directions. Deterministic, and Gaussian by the central limit
// theorem, which is what the blend's claim is about. (The shipped cascades are the same shape of
// object: a sum of many random-phase modes.)
struct SynthSea {
    static constexpr int kModes = 100;
    double kx[kModes], kz[kModes], ph[kModes], amp[kModes];
    SynthSea() {
        uint64_t s = 0x1234567;
        auto rnd = [&s]() {
            s = WaveChart::Mix(s);
            return double(s >> 11) / 9007199254740992.0;
        };
        double p2 = 0.0;
        for (int i = 0; i < kModes; ++i) {
            const double lam = 8.0 + 180.0 * rnd();          // 8..188 m: broadband
            const double th = 6.28318530717959 * rnd();
            kx[i] = 6.28318530717959 / lam * std::cos(th);
            kz[i] = 6.28318530717959 / lam * std::sin(th);
            ph[i] = 6.28318530717959 * rnd();
            amp[i] = 1.0 / std::sqrt(double(kModes));
            p2 += amp[i] * amp[i] * 0.5;
        }
        (void)p2;
    }
    double At(const double u[2]) const {
        double h = 0.0;
        for (int i = 0; i < kModes; ++i) h += amp[i] * std::cos(kx[i] * u[0] + kz[i] * u[1] + ph[i]);
        return h;
    }
};

void DirOf(double latDeg, double lonDeg, double d[3]) {
    const double r = 3.14159265358979323846 / 180.0;
    const double cl = std::cos(latDeg * r);
    d[0] = cl * std::cos(lonDeg * r);
    d[1] = std::sin(latDeg * r);
    d[2] = cl * std::sin(lonDeg * r);
}

// The blend itself, as both processors run it.
double Blend(const WaveChart::Chart* c, int n, const SynthSea& sea) {
    double s = 0.0;
    for (int i = 0; i < n; ++i) s += c[i].w * sea.At(c[i].u);
    return s / WaveChart::Norm(c, n);
}

}  // namespace

bool RunWaveChartSelfTest() {
    WaveChart wc;   // the shipped defaults: level 5, a 5 km band
    const SynthSea sea;
    int checks = 0;
    bool ok = true;
    auto fail = [&](const char* what, double got, double want) {
        Log("[wavechart] FAIL: %s -- %.9g against %.9g", what, got, want);
        ok = false;
    };

    // ---- 1. the partition, over the whole sphere ------------------------------------------
    {
        double worstSum = 0.0;
        int maxN = 0, bands = 0, corners = 0;
        for (int i = 0; i < 4001; ++i) {
            const double lat = -89.0 + 178.0 * (double(i % 97) / 96.0);
            const double lon = -180.0 + 360.0 * (double(i % 101) / 100.0);
            double d[3];
            DirOf(lat, lon, d);
            WaveChart::Chart c[WaveChart::kMax];
            const int n = wc.At(d, c);
            double sum = 0.0;
            for (int k = 0; k < n; ++k) sum += c[k].w;
            worstSum = (std::max)(worstSum, std::fabs(sum - 1.0));
            maxN = (std::max)(maxN, n);
            if (n == 2) ++bands;
            if (n >= 3) ++corners;
            ++checks;
        }
        if (worstSum > 1e-12) fail("the shares sum to 1", worstSum, 0.0);
        if (maxN > WaveChart::kMax) fail("at most four charts", double(maxN), double(WaveChart::kMax));
        Log("[wavechart] the partition holds over %d places (worst |sum - 1| %.1e; %d in a band, "
            "%d at a corner -- %.1f %% of places read one chart)",
            4001, worstSum, bands, corners, 100.0 * double(4001 - bands - corners) / 4001.0);
    }

    // ---- 2. continuity across a cell edge, and across a cube-face edge ----------------------
    {
        // A line 12 km long crossing a cell boundary: find one by walking east until the cell
        // address changes, then sample 1 m apart across it.
        double d[3];
        DirOf(42.8, -70.8, d);
        WaveChart::Chart c0[WaveChart::kMax];
        wc.At(d, c0);
        const uint64_t home = c0[0].cell;
        double lonEdge = -70.8;
        bool found = false;
        for (int i = 1; i < 400000 && !found; ++i) {
            const double lon = -70.8 + 0.001 * i;
            DirOf(42.8, lon, d);
            WaveChart::Chart c[WaveChart::kMax];
            wc.At(d, c);
            if (c[0].cell != home) {
                lonEdge = lon;
                found = true;
            }
        }
        if (!found) fail("a cell edge exists east of the anchor", 0.0, 1.0);
        // Three series over the same line, one metre a step: the blend; ONE chart's realization
        // (what the field itself does in a metre -- the scale a continuous law may move at); and
        // the gap between the two charts at each place (what a hard switch would jump by the
        // moment it changed hands).
        double worstStep = 0.0, worstOwn = 0.0, worstGap = 0.0;
        double prev = 0.0, prevOwn = 0.0;
        const double mPerDeg = 111195.0 * std::cos(42.8 * 3.14159265358979323846 / 180.0);
        for (int i = -6000; i <= 6000; ++i) {
            const double lon = lonEdge + double(i) / mPerDeg;   // one metre a step
            DirOf(42.8, lon, d);
            WaveChart::Chart c[WaveChart::kMax];
            const int n = wc.At(d, c);
            const double h = Blend(c, n, sea);
            const double own = sea.At(c[0].u);
            if (i > -6000) {
                worstStep = (std::max)(worstStep, std::fabs(h - prev));
                worstOwn = (std::max)(worstOwn, std::fabs(own - prevOwn));
            }
            if (n > 1) worstGap = (std::max)(worstGap, std::fabs(own - sea.At(c[1].u)));
            prev = h;
            prevOwn = own;
            ++checks;
        }
        // The blend may not move faster than the field it is made of: a hard switch would step by
        // the two charts' whole difference (worstGap) the moment it changed hands.
        if (!(worstStep <= 1.5 * worstOwn)) {
            fail("the blend moves no faster than the field", worstStep, 1.5 * worstOwn);
        }
        Log("[wavechart] across a cell edge, one metre a step over 12 km: the blend's worst step "
            "%.4f, the field's own %.4f, the two charts' gap (what a switch would jump) %.4f",
            worstStep, worstOwn, worstGap);
    }

    // ---- 3. variance, the whole reason for the operator -------------------------------------
    {
        // Straddle a cube-face edge as well, so the canonical-neighbour path is measured too.
        double v1 = 0.0, vB = 0.0;
        int n1 = 0, nB = 0;
        for (int i = 0; i < 20000; ++i) {
            const double lat = -60.0 + 120.0 * (double(i % 137) / 136.0);
            const double lon = -180.0 + 360.0 * (double(i % 149) / 148.0);
            double d[3];
            DirOf(lat, lon, d);
            WaveChart::Chart c[WaveChart::kMax];
            const int n = wc.At(d, c);
            const double h = Blend(c, n, sea);
            if (n == 1) {
                v1 += h * h;
                ++n1;
            } else {
                vB += h * h;
                ++nB;
            }
            ++checks;
        }
        const double s1 = (n1 > 0) ? std::sqrt(v1 / n1) : 0.0;
        const double sB = (nB > 0) ? std::sqrt(vB / nB) : 0.0;
        const double ratio = (s1 > 0.0) ? sB / s1 : 0.0;
        // A plain lerp would read about 1/sqrt(2) = 0.71 in the middle of a band; the operator
        // holds 1. (The sample is finite, so the band is allowed a few per cent of scatter.)
        if (nB > 200 && !(ratio > 0.93 && ratio < 1.07)) {
            fail("the blend preserves variance in a band", ratio, 1.0);
        }
        Log("[wavechart] variance: rms %.4f on one chart (n %d), %.4f in a band (n %d) -- ratio "
            "%.3f, where a lerp reads 0.71", s1, n1, sB, nB, ratio);
    }

    // ---- 4. the metric: a tangent projection over a cell 400 km across -----------------------
    {
        double worst = 0.0;
        for (int i = 0; i < 200; ++i) {
            const double lat = -70.0 + 140.0 * (double(i) / 199.0);
            double d0[3], d1[3];
            DirOf(lat, 10.0, d0);
            WaveChart::Chart a[WaveChart::kMax], b[WaveChart::kMax];
            wc.At(d0, a);
            // A point 1 km further east, read in the SAME chart: the plane's distance against
            // the sphere's own.
            const double mPerDeg = 111195.0 * std::cos(lat * 3.14159265358979323846 / 180.0);
            DirOf(lat, 10.0 + 1000.0 / mPerDeg, d1);
            wc.At(d1, b);
            if (a[0].cell != b[0].cell) continue;
            const double du = b[0].u[0] - a[0].u[0], dv = b[0].u[1] - a[0].u[1];
            const double inPlane = std::sqrt(du * du + dv * dv);
            worst = (std::max)(worst, std::fabs(inPlane - 1000.0) / 1000.0);
            ++checks;
        }
        if (!(worst < 1.0e-3)) fail("the chart's metric over a cell", worst, 1.0e-3);
        Log("[wavechart] the tangent projection's worst distance error inside a cell: %.4f %% "
            "(a wavelength of 100 m read as %.4f m)", worst * 100.0, 100.0 * (1.0 - worst));
    }

    // ---- 5. determinism ---------------------------------------------------------------------
    {
        double d[3];
        DirOf(25.8997, -80.1239, d);   // Haulover, the place this whole pass is about
        WaveChart::Chart a[WaveChart::kMax], b[WaveChart::kMax];
        const int na = wc.At(d, a);
        const int nb = wc.At(d, b);
        bool same = na == nb;
        for (int i = 0; i < na && same; ++i) {
            same = a[i].cell == b[i].cell && a[i].w == b[i].w && a[i].u[0] == b[i].u[0] &&
                   a[i].u[1] == b[i].u[1];
        }
        if (!same) fail("the same place answers the same charts", 0.0, 1.0);
        ++checks;
    }

    Log("[wavechart] ---- %s (%d checks): the partition and its four-chart bound, continuity "
        "across a cell edge and a face edge, the variance-preserving blend against a lerp's 0.71, "
        "the tangent projection's metric inside a cell, determinism at Haulover ----",
        ok ? "PASS" : "FAIL", checks);
    return ok;
}

}  // namespace ga
